version: '3.8'
services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      - APP_NAME=alexstraszaCMS
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://example.com